ecr_repo_one     = "podaac-sst-one"
ecr_repo_two     = "podaac-sst-two"
ecr_repo_three   = "podaac-sst-three"
edl_password = ""
edl_username = ""
lambda_role  = "podaac-sst-lambda-role"
prefix       = "podaac"
profile      = "saml-pub"
